# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-07 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issueview', '0004_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='issueview.Board'),
        ),
        migrations.AddField(
            model_name='repository',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='issueview.Board'),
        ),
    ]
