# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-07 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueview', '0009_remove_issue_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repository',
            field=models.CharField(max_length=100),
        ),
    ]
