# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-07 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueview', '0010_auto_20161207_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readpermissions',
            name='user',
        ),
        migrations.AddField(
            model_name='readpermissions',
            name='username',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
