# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueview', '0012_oauthcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.CharField(default='', max_length=200),
        ),
    ]
